name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 3'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fc_version: [ 32, 33, 34, 35 ]
    name: "Build yocto:${{ matrix.fc_version}}"
    env:
      FULL_IMAGE_TAG: "yocto:${{ matrix.fc_version }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file fedora-${{ matrix.fc_version }}/Dockerfile --tag ${FULL_IMAGE_TAG} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: fedora-${{ matrix.fc_version}}/Dockerfile
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman push localhost/${FULL_IMAGE_TAG} ghcr.io/${{ github.repository }}/${FULL_IMAGE_TAG}
          if [[ ${{ matrix.fc_version}} -eq 34 ]]; then
            podman push localhost/${FULL_IMAGE_TAG} ghcr.io/${{ github.repository }}/yocto:latest
          fi
