name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 3'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fc_version: [ 36, 37, 38 ]
    name: "Build yocto:${{ matrix.fc_version}}"
    env:
      FULL_IMAGE_NAME: "ghcr.io/${{ github.repository }}/yocto"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file yocto-fc/Dockerfile \
            --build-arg FC_VERSION=${{ matrix.fc_version }} \
            --tag ${FULL_IMAGE_NAME}:${{ matrix.fc_version }} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          podman login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          podman push ${FULL_IMAGE_NAME}:${{ matrix.fc_version }}

  hadolint:
    runs-on: ubuntu-latest
    name: "Hadolint"
    steps:
      - uses: actions/checkout@main
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
