name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 3'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: "Build"
    env:
      IMAGE_NAME: yocto
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: podman build --tag ${IMAGE_NAME} .
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          podman push localhost/${IMAGE_NAME} ghcr.io/${{ github.repository }}/${IMAGE_NAME}